//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeltTempLookup.IDTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.idtdna.com/", ConfigurationName="IDTService.OligoAnalyzerSoap")]
    public interface OligoAnalyzerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.idtdna.com/Analyze", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MeltTempLookup.IDTService.AnalyzerResult Analyze(string Sequence, string TargetType, double OligoConc, double NaConc, double MgConc, double dNTPsConc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.idtdna.com/Analyze", ReplyAction="*")]
        System.Threading.Tasks.Task<MeltTempLookup.IDTService.AnalyzerResult> AnalyzeAsync(string Sequence, string TargetType, double OligoConc, double NaConc, double MgConc, double dNTPsConc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.idtdna.com/HeteroDimer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MeltTempLookup.IDTService.TDuplexResults HeteroDimer(string Sequence, string SecondarySequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.idtdna.com/HeteroDimer", ReplyAction="*")]
        System.Threading.Tasks.Task<MeltTempLookup.IDTService.TDuplexResults> HeteroDimerAsync(string Sequence, string SecondarySequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.idtdna.com/SelfDimer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MeltTempLookup.IDTService.TDuplexResults SelfDimer(string Sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.idtdna.com/SelfDimer", ReplyAction="*")]
        System.Threading.Tasks.Task<MeltTempLookup.IDTService.TDuplexResults> SelfDimerAsync(string Sequence);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.idtdna.com/")]
    public partial class AnalyzerResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sequenceField;
        
        private string complementField;
        
        private string targetTypeField;
        
        private int sequenceLengthField;
        
        private double gCPctgField;
        
        private double minMeltTempField;
        
        private double meltTempField;
        
        private double maxMeltTempField;
        
        private double molecularWeightField;
        
        private double extCoeffField;
        
        private double nMolePerODField;
        
        private double uGramsPerODField;
        
        private bool hasMixedElementsField;
        
        private bool hasErrorsField;
        
        private AnalyzerError[] errorsField;
        
        private Modification[] modificationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
                this.RaisePropertyChanged("Complement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TargetType {
            get {
                return this.targetTypeField;
            }
            set {
                this.targetTypeField = value;
                this.RaisePropertyChanged("TargetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SequenceLength {
            get {
                return this.sequenceLengthField;
            }
            set {
                this.sequenceLengthField = value;
                this.RaisePropertyChanged("SequenceLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double GCPctg {
            get {
                return this.gCPctgField;
            }
            set {
                this.gCPctgField = value;
                this.RaisePropertyChanged("GCPctg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double MinMeltTemp {
            get {
                return this.minMeltTempField;
            }
            set {
                this.minMeltTempField = value;
                this.RaisePropertyChanged("MinMeltTemp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double MeltTemp {
            get {
                return this.meltTempField;
            }
            set {
                this.meltTempField = value;
                this.RaisePropertyChanged("MeltTemp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double MaxMeltTemp {
            get {
                return this.maxMeltTempField;
            }
            set {
                this.maxMeltTempField = value;
                this.RaisePropertyChanged("MaxMeltTemp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double MolecularWeight {
            get {
                return this.molecularWeightField;
            }
            set {
                this.molecularWeightField = value;
                this.RaisePropertyChanged("MolecularWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double ExtCoeff {
            get {
                return this.extCoeffField;
            }
            set {
                this.extCoeffField = value;
                this.RaisePropertyChanged("ExtCoeff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double nMolePerOD {
            get {
                return this.nMolePerODField;
            }
            set {
                this.nMolePerODField = value;
                this.RaisePropertyChanged("nMolePerOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double uGramsPerOD {
            get {
                return this.uGramsPerODField;
            }
            set {
                this.uGramsPerODField = value;
                this.RaisePropertyChanged("uGramsPerOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool HasMixedElements {
            get {
                return this.hasMixedElementsField;
            }
            set {
                this.hasMixedElementsField = value;
                this.RaisePropertyChanged("HasMixedElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool HasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
                this.RaisePropertyChanged("HasErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public AnalyzerError[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public Modification[] Modifications {
            get {
                return this.modificationsField;
            }
            set {
                this.modificationsField = value;
                this.RaisePropertyChanged("Modifications");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.idtdna.com/")]
    public partial class AnalyzerError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTextField;
        
        private string errorSymbolField;
        
        private string errorSeverityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorSymbol {
            get {
                return this.errorSymbolField;
            }
            set {
                this.errorSymbolField = value;
                this.RaisePropertyChanged("ErrorSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorSeverity {
            get {
                return this.errorSeverityField;
            }
            set {
                this.errorSeverityField = value;
                this.RaisePropertyChanged("ErrorSeverity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.idtdna.com/")]
    public partial class TDuplexMatch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double deltaGField;
        
        private int start_PosField;
        
        private int base_PairsField;
        
        private int[] bondsField;
        
        private int topLinePaddingField;
        
        private int bondLinePaddingField;
        
        private int bottomLinePaddingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double DeltaG {
            get {
                return this.deltaGField;
            }
            set {
                this.deltaGField = value;
                this.RaisePropertyChanged("DeltaG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Start_Pos {
            get {
                return this.start_PosField;
            }
            set {
                this.start_PosField = value;
                this.RaisePropertyChanged("Start_Pos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Base_Pairs {
            get {
                return this.base_PairsField;
            }
            set {
                this.base_PairsField = value;
                this.RaisePropertyChanged("Base_Pairs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public int[] Bonds {
            get {
                return this.bondsField;
            }
            set {
                this.bondsField = value;
                this.RaisePropertyChanged("Bonds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TopLinePadding {
            get {
                return this.topLinePaddingField;
            }
            set {
                this.topLinePaddingField = value;
                this.RaisePropertyChanged("TopLinePadding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int BondLinePadding {
            get {
                return this.bondLinePaddingField;
            }
            set {
                this.bondLinePaddingField = value;
                this.RaisePropertyChanged("BondLinePadding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int BottomLinePadding {
            get {
                return this.bottomLinePaddingField;
            }
            set {
                this.bottomLinePaddingField = value;
                this.RaisePropertyChanged("BottomLinePadding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.idtdna.com/")]
    public partial class TDuplexResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string primarySeqField;
        
        private string secondarySeqField;
        
        private double complementarityPercentField;
        
        private TDuplexMatch[] dimerInfoField;
        
        private bool isComplementPairField;
        
        private int longestCCPField;
        
        private double molWgtHyField;
        
        private int offsetOfLongestCCPField;
        
        private int shortOligoLengthField;
        
        private bool primarySeqHasErrorsField;
        
        private bool secondarySeqHasErrorsField;
        
        private double maxDeltaGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PrimarySeq {
            get {
                return this.primarySeqField;
            }
            set {
                this.primarySeqField = value;
                this.RaisePropertyChanged("PrimarySeq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SecondarySeq {
            get {
                return this.secondarySeqField;
            }
            set {
                this.secondarySeqField = value;
                this.RaisePropertyChanged("SecondarySeq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double ComplementarityPercent {
            get {
                return this.complementarityPercentField;
            }
            set {
                this.complementarityPercentField = value;
                this.RaisePropertyChanged("ComplementarityPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public TDuplexMatch[] DimerInfo {
            get {
                return this.dimerInfoField;
            }
            set {
                this.dimerInfoField = value;
                this.RaisePropertyChanged("DimerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsComplementPair {
            get {
                return this.isComplementPairField;
            }
            set {
                this.isComplementPairField = value;
                this.RaisePropertyChanged("IsComplementPair");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int LongestCCP {
            get {
                return this.longestCCPField;
            }
            set {
                this.longestCCPField = value;
                this.RaisePropertyChanged("LongestCCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double MolWgtHy {
            get {
                return this.molWgtHyField;
            }
            set {
                this.molWgtHyField = value;
                this.RaisePropertyChanged("MolWgtHy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int OffsetOfLongestCCP {
            get {
                return this.offsetOfLongestCCPField;
            }
            set {
                this.offsetOfLongestCCPField = value;
                this.RaisePropertyChanged("OffsetOfLongestCCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ShortOligoLength {
            get {
                return this.shortOligoLengthField;
            }
            set {
                this.shortOligoLengthField = value;
                this.RaisePropertyChanged("ShortOligoLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool PrimarySeqHasErrors {
            get {
                return this.primarySeqHasErrorsField;
            }
            set {
                this.primarySeqHasErrorsField = value;
                this.RaisePropertyChanged("PrimarySeqHasErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool SecondarySeqHasErrors {
            get {
                return this.secondarySeqHasErrorsField;
            }
            set {
                this.secondarySeqHasErrorsField = value;
                this.RaisePropertyChanged("SecondarySeqHasErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double MaxDeltaG {
            get {
                return this.maxDeltaGField;
            }
            set {
                this.maxDeltaGField = value;
                this.RaisePropertyChanged("MaxDeltaG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.idtdna.com/")]
    public partial class Modification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortNameField;
        
        private string productNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OligoAnalyzerSoapChannel : MeltTempLookup.IDTService.OligoAnalyzerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OligoAnalyzerSoapClient : System.ServiceModel.ClientBase<MeltTempLookup.IDTService.OligoAnalyzerSoap>, MeltTempLookup.IDTService.OligoAnalyzerSoap {
        
        public OligoAnalyzerSoapClient() {
        }
        
        public OligoAnalyzerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OligoAnalyzerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OligoAnalyzerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OligoAnalyzerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MeltTempLookup.IDTService.AnalyzerResult Analyze(string Sequence, string TargetType, double OligoConc, double NaConc, double MgConc, double dNTPsConc) {
            return base.Channel.Analyze(Sequence, TargetType, OligoConc, NaConc, MgConc, dNTPsConc);
        }
        
        public System.Threading.Tasks.Task<MeltTempLookup.IDTService.AnalyzerResult> AnalyzeAsync(string Sequence, string TargetType, double OligoConc, double NaConc, double MgConc, double dNTPsConc) {
            return base.Channel.AnalyzeAsync(Sequence, TargetType, OligoConc, NaConc, MgConc, dNTPsConc);
        }
        
        public MeltTempLookup.IDTService.TDuplexResults HeteroDimer(string Sequence, string SecondarySequence) {
            return base.Channel.HeteroDimer(Sequence, SecondarySequence);
        }
        
        public System.Threading.Tasks.Task<MeltTempLookup.IDTService.TDuplexResults> HeteroDimerAsync(string Sequence, string SecondarySequence) {
            return base.Channel.HeteroDimerAsync(Sequence, SecondarySequence);
        }
        
        public MeltTempLookup.IDTService.TDuplexResults SelfDimer(string Sequence) {
            return base.Channel.SelfDimer(Sequence);
        }
        
        public System.Threading.Tasks.Task<MeltTempLookup.IDTService.TDuplexResults> SelfDimerAsync(string Sequence) {
            return base.Channel.SelfDimerAsync(Sequence);
        }
    }
}
